# .github/workflows/ci.yml
name: CI
  
on: [push, pull_request]

jobs:  
  run-tests:  
    strategy:
      fail-fast: false  
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]  
    
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          sudo apt-get -y install graphviz libgraphviz-dev pkg-config
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
          python -m pip install pytest coverage
      - name: Test with pytest  
        run: |  
          coverage run -m pytest -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
